global:
  name: LF Public Health Landscape
  short_name: LFPH
  repo: lfph/lfph-landscape
  website: 'https://landscape.lfph.io'
  short_domain: l.lfph.io
  company_url: 'https://lfph.io'
  email: info@lfph.io
  self: 'https://www.crunchbase.com/organization/lf-public-health'
  slack_channel: T01382K7DLP/B013JERTXUP/QEQpPKsCj4XhawCP3B1USSyA
  meta:
    title: LF Public Health Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@lfpublichealth'
    google_site_verification: u_xqWIf8_EzRP4UF92px16rTSoIP49D_g9i7M-4rXds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: LF Public Health Foundation Member
  flags:
    hide_license_for_categories:
      - LF Public Health Adopter
      - LF Public Health Foundation Member
twitter:
  search: landscape.lfph.io
  url: 'https://landscape.lfph.io'
  text: LF Public Health Landscape
relation:
  label: LF Public Health Relation
  url: LF Public Health
  values:
    - id: hosted
      label: LF Public Health Foundation Projects
      children:
        - id: foundationproject
          label: LF Public Health Foundation Projects
          prefix: LF Public Health
          tag: Foundation Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Public Health Foundation Project
          big_picture_color: 'rgb(24,54,114)'
    - id: company
      label: LF Public Health Foundation Member
      tag: Company
      big_picture_order: 3
    - id: member
      label: LF Public Health Foundation Member Products/Projects
      tag: LF Public Health Foundation Member
    - id: false
      label: Non-LF Public Health Foundation Member Products/Projects
      url: 'no'
membership:
  General:
    name: LF Public Health
    label: Member
    funding: General
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: 'https://www.crunchbase.com/organization/linux-foundation'
  'false':
    funding: 'No'
home:
  header: >
    <h1>LF Public Health Landscape</h1> The LF Public Health Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: 'https://events.linuxfoundation.org/open-source-summit-north-america/?utm_source=LF Public Health_landscape&utm_medium=web&utm_campaign=ossna20'
    image: /images/info2.jpg
    title: Open Source Summit North America 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: LF Public Health Landscape
    fullscreen_header: See the interactive landscape at l.lfph.io
    elements:
      - type: HorizontalCategory
        category: Projects
        rows: 4
        width: 325
        height: 160
        top: 0
        left: 0
        color: 'rgb(4,81,49)'
        fit_width: true
      - type: HorizontalCategory
        category: Specifications
        rows: 3
        width: 280
        height: 160
        top: 0
        left: 345
        color: 'rgb(7,136,62)'
        fit_width: true
      - type: HorizontalCategory
        category: Components
        rows: 3
        width: 325
        height: 160
        top: 0
        left: 645
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: VerticalCategory
        category: Organizations
        cols: 3
        width: 160
        height: 325
        top: 0
        left: 990
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: HorizontalCategory
        category: LF Public Health Adopter
        rows: 6
        width: 970
        height: 320
        top: 180
        left: 0
        color: 'rgb(126,115,14)'
        fit_width: true
      - type: HorizontalCategory
        category: LF Public Health Foundation Member
        rows: 4
        width: 650
        height: 200
        top: 540
        left: 0
        color: 'rgb(103,66,18)'
        fit_width: true
      - type: LandscapeInfo
        width: 310
        height: 200
        top: 540
        left: 665
        children:
          - type: text
            text: >
              This landscape is intended as a map to explore the LF Public Health community, and also shows the member organizations of the LF Public Health
              Foundation.
            top: 55
            left: 140
            right: 10
            font_size: 10
          - type: image
            image: qr.svg
            top: 55
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.lfph.io
            top: 140
            left: 5
            font_size: 21
          - type: image
            image: left-logo.svg
            width: 110
            right: 190
            top: 10
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 109
            right: 10
            top: 10
            title: LF Public Health Foundation Logo
test:
  header: LF Public Health Landscape
  section: LF Public Health Foundation Member
  logo: u-s-digital-response.svg
