global:
  name: LF Public Health Landscape
  short_name: LFPH
  repo: lfph/lfph-landscape
  website: 'https://landscape.lfph.io'
  short_domain: l.lfph.io
  company_url: 'https://lfph.io'
  email: info@lfph.io
  self: 'https://www.crunchbase.com/organization/lf-public-health'
  slack_channel: T01382K7DLP/B013JERTXUP/QEQpPKsCj4XhawCP3B1USSyA
  meta:
    title: LF Public Health Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@lfpublichealth'
    google_site_verification: u_xqWIf8_EzRP4UF92px16rTSoIP49D_g9i7M-4rXds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    hide_license_for_categories:
      - LF Public Health Adopter
  membership: LFPH Member
twitter:
  search: landscape.lfph.io
  url: 'https://landscape.lfph.io'
  text: LF Public Health Landscape
relation:
  label: LF Public Health Relation
  url: LF Public Health
  values:
    - id: hosted
      label: LF Public Health Foundation Projects
      children:
        - id: foundationproject
          label: LF Public Health Foundation Projects
          prefix: LF Public Health
          tag: Foundation Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Public Health Foundation Project
          big_picture_color: 'rgb(24,54,114)'
    - id: member
      label: LFPH Member Products/Projects
      tag: LF Public Health Foundation Member
    - id: false
      label: Non-LFPH Member Products/Projects
      url: 'no'
membership:
  General:
    name: LF Public Health
    label: Member
    funding: General
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: 'https://www.crunchbase.com/organization/linux-foundation'
  'false':
    funding: 'No'
home:
  header: >
    <h1>LF Public Health Landscape</h1> The LF Public Health Foundation landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: 'https://events.linuxfoundation.org/open-source-summit-north-america/?utm_source=LF Public Health_landscape&utm_medium=web&utm_campaign=ossna20'
    image: /images/info2.jpg
    title: Open Source Summit North America 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: LF Public Health Landscape
    fullscreen_header: See the online landscape at l.lfph.io
    elements:
      - type: HorizontalCategory
        category: Exposure Notification
        width: 390
        height: 120
        top: 0
        left: 0
        color: 'rgb(4,81,49)'
        fit_width: true
      - type: HorizontalCategory
        category: Specification
        width: 150
        height: 120
        top: 0
        left: 420
        color: 'rgb(7,136,62)'
        fit_width: true
      - type: HorizontalCategory
        category: Contact Tracing
        width: 150
        height: 120
        top: 0
        left: 600
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: HorizontalCategory
        category: Symptom Monitoring
        width: 200
        height: 100
        top: 140
        left: 0
        color: 'rgb(126,115,14)'
        fit_width: true
      - type: HorizontalCategory
        category: Non-Code Contribution
        width: 200
        height: 100
        top: 140
        left: 230
        color: 'rgb(143,88,61)'
        fit_width: true
      - type: HorizontalCategory
        category: PHA-Deployed App
        rows: 6
        width: 750
        height: 120
        top: 260
        left: 0
        color: 'rgb(179,77,77)'
        fit_width: true
      - type: LandscapeInfo
        width: 290
        height: 130
        top: 110
        left: 460
        children:
          - type: text
            text: >-
              This landscape is a map to explore the software that is being developed to combat COVID-19, and focuses particularly on Google Apple Exposure
              Notification (GAEN) implementations and the apps deployed by public health authorities (PHAs).
            top: 30
            left: 95
            right: 10
            font_size: 9
          - type: image
            image: qr.svg
            top: 5
            left: 10
            width: 80
            height: 80
            title: QR Code
          - type: title
            title: l.lfph.io
            top: 87
            left: 20
            font_size: 16
          - type: image
            image: left-logo.svg
            width: 80
            right: 110
            top: 5
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 80
            right: 15
            top: 5
            title: LF Public Health Foundation Logo
anonymous_organization:
  name: Non-Public Unnamed Organization
  homepage: 'https://www.lfph.io'
  city: Bouvet Island
  region: Antarctica
  country: Antarctica
test:
  header: LF Public Health Landscape
  section: LFPH Member Products/Projects
  logo: covid-shield.svg
